### ISSUE TITLE
Use `login_headertitle` as filter to add text logo

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/colorlib-login-customizer#24]
Right now, CLC only supports image logo. Let's add logo text support as well.

**Comment by giucu91** [comment]
This will not work for the main site of a multi site installation.

**Comment by cristianraiber** [comment]
@giucu91 - known limitation. Here's the reason: https://github.com/WordPress/WordPress/blob/master/wp-login.php#L145

In a MultiSite instance, the site title is used.
